name: Fundamental Analysis Update

on:
  workflow_dispatch:

jobs:
  update-fundamentals:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install gspread oauth2client

      - name: Run Fundamental Analysis
        env:
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        run: |
          python update_fundamentals.py
